// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Employee.proto

package com.praba.protobuf;

public final class EmployeeProto {
  private EmployeeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EmployeeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Employee)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string firstname = 1;</code>
     */
    boolean hasFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    java.lang.String getFirstname();
    /**
     * <code>required string firstname = 1;</code>
     */
    com.google.protobuf.ByteString
        getFirstnameBytes();

    /**
     * <code>optional string lastname = 2;</code>
     */
    boolean hasLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    java.lang.String getLastname();
    /**
     * <code>optional string lastname = 2;</code>
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>required int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    boolean hasSalary();
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    double getSalary();
  }
  /**
   * Protobuf type {@code Employee}
   */
  public  static final class Employee extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Employee)
      EmployeeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Employee.newBuilder() to construct.
    private Employee(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Employee() {
      firstname_ = "";
      lastname_ = "";
      id_ = 0;
      salary_ = 100000D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Employee(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              firstname_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              lastname_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              salary_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.praba.protobuf.EmployeeProto.internal_static_Employee_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.praba.protobuf.EmployeeProto.internal_static_Employee_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.praba.protobuf.EmployeeProto.Employee.class, com.praba.protobuf.EmployeeProto.Employee.Builder.class);
    }

    private int bitField0_;
    public static final int FIRSTNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object firstname_;
    /**
     * <code>required string firstname = 1;</code>
     */
    public boolean hasFirstname() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public java.lang.String getFirstname() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          firstname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string firstname = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFirstnameBytes() {
      java.lang.Object ref = firstname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object lastname_;
    /**
     * <code>optional string lastname = 2;</code>
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string lastname = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>required int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int SALARY_FIELD_NUMBER = 4;
    private double salary_;
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public boolean hasSalary() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional double salary = 4 [default = 100000];</code>
     */
    public double getSalary() {
      return salary_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFirstname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, firstname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, salary_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, firstname_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, lastname_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, salary_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.praba.protobuf.EmployeeProto.Employee)) {
        return super.equals(obj);
      }
      com.praba.protobuf.EmployeeProto.Employee other = (com.praba.protobuf.EmployeeProto.Employee) obj;

      boolean result = true;
      result = result && (hasFirstname() == other.hasFirstname());
      if (hasFirstname()) {
        result = result && getFirstname()
            .equals(other.getFirstname());
      }
      result = result && (hasLastname() == other.hasLastname());
      if (hasLastname()) {
        result = result && getLastname()
            .equals(other.getLastname());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasSalary() == other.hasSalary());
      if (hasSalary()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSalary())
            == java.lang.Double.doubleToLongBits(
                other.getSalary()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFirstname()) {
        hash = (37 * hash) + FIRSTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getFirstname().hashCode();
      }
      if (hasLastname()) {
        hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastname().hashCode();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasSalary()) {
        hash = (37 * hash) + SALARY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSalary()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.praba.protobuf.EmployeeProto.Employee parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.praba.protobuf.EmployeeProto.Employee prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Employee}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Employee)
        com.praba.protobuf.EmployeeProto.EmployeeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.praba.protobuf.EmployeeProto.internal_static_Employee_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.praba.protobuf.EmployeeProto.internal_static_Employee_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.praba.protobuf.EmployeeProto.Employee.class, com.praba.protobuf.EmployeeProto.Employee.Builder.class);
      }

      // Construct using com.praba.protobuf.EmployeeProto.Employee.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        firstname_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        salary_ = 100000D;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.praba.protobuf.EmployeeProto.internal_static_Employee_descriptor;
      }

      public com.praba.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
        return com.praba.protobuf.EmployeeProto.Employee.getDefaultInstance();
      }

      public com.praba.protobuf.EmployeeProto.Employee build() {
        com.praba.protobuf.EmployeeProto.Employee result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.praba.protobuf.EmployeeProto.Employee buildPartial() {
        com.praba.protobuf.EmployeeProto.Employee result = new com.praba.protobuf.EmployeeProto.Employee(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.firstname_ = firstname_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lastname_ = lastname_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.salary_ = salary_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.praba.protobuf.EmployeeProto.Employee) {
          return mergeFrom((com.praba.protobuf.EmployeeProto.Employee)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.praba.protobuf.EmployeeProto.Employee other) {
        if (other == com.praba.protobuf.EmployeeProto.Employee.getDefaultInstance()) return this;
        if (other.hasFirstname()) {
          bitField0_ |= 0x00000001;
          firstname_ = other.firstname_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000002;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSalary()) {
          setSalary(other.getSalary());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFirstname()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.praba.protobuf.EmployeeProto.Employee parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.praba.protobuf.EmployeeProto.Employee) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstname_ = "";
      /**
       * <code>required string firstname = 1;</code>
       */
      public boolean hasFirstname() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public java.lang.String getFirstname() {
        java.lang.Object ref = firstname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            firstname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFirstnameBytes() {
        java.lang.Object ref = firstname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder clearFirstname() {
        bitField0_ = (bitField0_ & ~0x00000001);
        firstname_ = getDefaultInstance().getFirstname();
        onChanged();
        return this;
      }
      /**
       * <code>required string firstname = 1;</code>
       */
      public Builder setFirstnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        firstname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>optional string lastname = 2;</code>
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string lastname = 2;</code>
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        lastname_ = value;
        onChanged();
        return this;
      }

      private int id_ ;
      /**
       * <code>required int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      private double salary_ = 100000D;
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public boolean hasSalary() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public double getSalary() {
        return salary_;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder setSalary(double value) {
        bitField0_ |= 0x00000008;
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double salary = 4 [default = 100000];</code>
       */
      public Builder clearSalary() {
        bitField0_ = (bitField0_ & ~0x00000008);
        salary_ = 100000D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Employee)
    }

    // @@protoc_insertion_point(class_scope:Employee)
    private static final com.praba.protobuf.EmployeeProto.Employee DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.praba.protobuf.EmployeeProto.Employee();
    }

    public static com.praba.protobuf.EmployeeProto.Employee getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Employee>
        PARSER = new com.google.protobuf.AbstractParser<Employee>() {
      public Employee parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Employee(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Employee> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Employee> getParserForType() {
      return PARSER;
    }

    public com.praba.protobuf.EmployeeProto.Employee getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Employee_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Employee_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Employee.proto\"S\n\010Employee\022\021\n\tfirstnam" +
      "e\030\001 \002(\t\022\020\n\010lastname\030\002 \001(\t\022\n\n\002id\030\003 \002(\005\022\026\n" +
      "\006salary\030\004 \001(\001:\006100000B#\n\022com.praba.proto" +
      "bufB\rEmployeeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Employee_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Employee_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Employee_descriptor,
        new java.lang.String[] { "Firstname", "Lastname", "Id", "Salary", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
